# fly.toml app configuration file generated for olympus-treasury-subgraph on 2023-09-25T11:35:09+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "olympus-treasury-subgraph"
primary_region = "bos"

[build]

[http_service]
  internal_port = 9991
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
